theme: jekyll-theme-minimal
title: Differentiable Agent-Based Models
description: Tutorial on differentiable ABMs at AAMAs 2024.
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one